sudo: required

language: node_js

node_js:
  - 4
  - 6
  - 8
  - 10

env:
  matrix:
    - MONGODB=3.4
    - MONGODB=3.6
    - MONGODB=4.0

services:
  - docker

before_script:
  - docker run -d -p 27017:27017 mongo:$MONGODB
  - docker ps -a

script:
  # - npm run lint
  # turn off lint for the moment
  - MONGODB_URL=mongodb://localhost/connect-mongo-test travis_retry npm test

after_success:
  - npm install coveralls -g && npm run cover | coveralls
